# Generated by Django 5.2.1 on 2025-06-03 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_stream_stream_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CameraAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_name', models.CharField(max_length=100)),
                ('angle_description', models.TextField(blank=True, null=True)),
                ('camera_url', models.URLField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_angles', to='stream.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='stream.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stream', 'user')},
            },
        ),
    ]
